/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -m -p timedated_interface /home/cutefish/CutefishOS/settings/src/datetime/org.freedesktop.timedate1.xml
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "timedated_interface.h"

/*
 * Implementation of interface class OrgFreedesktopTimedate1Interface
 */

OrgFreedesktopTimedate1Interface::OrgFreedesktopTimedate1Interface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgFreedesktopTimedate1Interface::~OrgFreedesktopTimedate1Interface()
{
}
